FROM node:20-alpine AS build
WORKDIR /app
ARG VITE_API_BASE_URL=http://localhost:5000/api/v1
ARG BASE_PATH=/
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV BASE_PATH=$BASE_PATH
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
